# Eureka Server ??? ?? ??? ????? 8761 ? ??
server:
  port: 8761

eureka:
  client:
    # ??? ?????? ??? ??? ??? ???? ?? ??
    register-with-eureka: false
    # ???? Service Registry ? ???? ?? ??
    # ?? ???? ????? ???? ?? ? ??? ??
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka