server:
  port: 8000

spring:
  application:
    name: gateway-server
    # api gateway ??? client ?? ??? ??
  cloud:
    gateway:
      routes:
        - id: 1st-service
          uri: lb://1ST-SERVICE
          predicates:
            - Path=/first-service/**
          filters:
            - RewritePath=/first-service/(?<segment>.*), /$\{segment}
        - id: 2st-service
          uri: lb://2ST-SERVICE
          predicates:
            - Path=/second-service/**
          filters:
            - RewritePath=/second-service/(?<segment>.*), /$\{segment}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka